services:
  pirate-dock:
    build: .
    container_name: pirate-dock
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun
    environment:
      - NORDVPN_TOKEN=${NORDVPN_TOKEN}
      - NORDVPN_LOGIN_TOKEN=${NORDVPN_LOGIN_TOKEN}
      - NORDVPN_COUNTRY=South_Africa
      - NORDVPN_TECHNOLOGY=NordLynx
      - NORDVPN_GROUP=P2P
      - HOME=/root
      - XDG_CONFIG_HOME=/root/.config
      - JACKETT_PORT=9118
    volumes:
      - ./downloads:/downloads
      - pirate-dock-data:/data
    ports:
      - "9876:9876"
      - "9118:9118"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv4.conf.all.src_valid_mark=1

volumes:
  pirate-dock-data:
